### ISSUE TITLE
Travis failed

### ISSUE THREAD

**Issue by qiushye** [tredoe/osutil#12]
`github.com/tredoe/osutil@v1.0.5 requires
github.com/tredoe/fileutil@v1.0.0: reading github.com/tredoe/fileutil/go.mod at revision v1.0.0: unknown revision v1.0.0`

Did it change recently? My project's travis worked normally yesterday.

**Comment by tredoe** [comment]
I'm trying fix it. I've recovered fileutil from a backup and I'm going to create v2 with new changes for osutil.

**Comment by tredoe** [comment]
Is it working now?

**Comment by tredoe** [comment]
Use v1.0.6 or v2.0.0 (although it is not stable)

**Comment by tredoe** [comment]
Somebody confirmes that v1.0.6 works without any breaking changes.
