### ISSUE TITLE
Different go.sum entries for different Go versions

### ISSUE THREAD

**Issue by chubin** [tredoe/osutil#13]
When I generate `go.sum` with go 1.16, and try to build it with go of a different version (1.13 in my case), I get `SECURITY ERROR`:

```
verifying github.com/tredoe/osutil@v1.1.1/go.mod: checksum mismatch
	downloaded: h1:fx79htI3WZA9Ep4jphLFq06l3iRDimfOWTrkKOz+OAA=
	go.sum:     h1:wHEjPMepmXQXkZhf9H4sQcCtmC45KuFo5VR97zG9/dY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

Then I fix (remove the entry and run `go mod tidy`) `go.sum` and try to build it again. It works with 1.13, but the problem appears then with 1.16.

Currently, as a workaround, I added this to my build scripts:

```
sed -i /osutil/d go.sum \
  && go mod download github.com/tredoe/osutil
```

but it is not a real solution, of course.

I have several hundreds of packages in `go.sum`, and the problem occurs only with this one, so I suspect there should be some version specific incompatibility in this package (I tested it with Go 1.13 and 1.16 only; not sure exactly when it was introduced, so don't know about 1.14 and 1.15).

Related information/discussions:

* https://groups.google.com/g/golang-nuts/c/a_cHjXkPWYg discussion in go-nuts
* https://stackoverflow.com/questions/68801097/ Question on StackOverflow

**Comment by tredoe** [comment]
Try a newer version

**Comment by tredoe** [comment]
I've done some changes that have broken the API because I removed the repository fileutil to add it here. I'd seen if my packages were beung used by some project of open source and since they weren't I decided to remove fileutil.

Sorry for the inconvenience! The only soliution is try to use the last version and fix the API in your application.

**Comment by tredoe** [comment]
I'm trying fix it. I've recovered fileutil from a backup and I'm going to create v2 with new changes for osutil.

**Comment by tredoe** [comment]
Is it working now?

**Comment by tredoe** [comment]
Use v1.0.6 or v2.0.0 (although it is not stable)

**Comment by tredoe** [comment]
Somebody confirmed to me that v1.0.6 works without any breaking changes

**Comment by chubin** [comment]
Something happened yesterday and now it is broken again.
If you try to build to build any project with it, you will get:

```
go: github.com/tredoe/osutil@v1.3.5 requires
	github.com/tredoe/goutil@v1.0.2: reading github.com/tredoe/goutil/go.mod at revision v1.0.2: unknown revision v1.0.2
```

**Comment by tredoe** [comment]
Use the version v1.0.6
