### ISSUE TITLE
Missing tag v1.1.0

### ISSUE THREAD

**Issue by yellowmint** [tredoe/osutil#15]
Version v1.1.0 is present in https://pkg.go.dev/github.com/tredoe/osutil?tab=versions but this repository does not have a corresponding tag.
It causes an error when listing possible module updates with `go list -json -m -u -mod=readonly all`. GoLand runs this command very often which results in reappearing errors.

Reproduce:

`main.go`
```golang
package main

import (
        "fmt"
        "github.com/tredoe/osutil/user/crypt/sha512_crypt"
)

func main() {
        c := sha512_crypt.New()
        hash, _ := c.Generate([]byte("password"), []byte{})
        fmt.Println("Hash: ", hash)
}
```

`go.mod`
```golang
module example.com

go 1.21

toolchain go1.21.0

require github.com/tredoe/osutil v1.0.6
```

```shell
$ go mod tidy
$ go list -json -m -u -mod=readonly all
go: reading github.com/tredoe/osutil/go.mod at revision v1.1.0: unknown revision v1.1.0
```

**Comment by tredoe** [comment]
Use version v1.5.0
