### ISSUE TITLE
Not able to use github.com/tredoe/osutil/user/crypt/sha512_crypt

### ISSUE THREAD

**Issue by jyothisjose** [tredoe/osutil#16]
While installing "github.com/tredoe/osutil/user/crypt/sha512_crypt" we are getting following error
	go: github.com/tredoe/osutil@v1.3.6 requires
	github.com/tredoe/fileutil@v1.0.5: reading github.com/tredoe/fileutil/go.mod at revision v1.0.5: git ls-remote -q origin in /go/pkg/mod/cache/vcs/e7809422632b0411766ef318a3bd6435b7dd89c78776ac18435e81058e602b19: exit status 128:
	 fatal: could not read Username for 'https://github.com': terminal prompts disabled
	Confirm the import path was entered correctly.
	If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

Can you please help us to resolve the error?

**Comment by jyothisjose** [comment]
@tredoe can you please look in to  the issue

**Comment by BirknerAlex** [comment]
This broke our pipeline as well, it seems the repository has been removed by @tredoe

**Comment by jyothisjose** [comment]
@BirknerAlex Have you done any alternate solution. if its so can you please let me know

**Comment by BirknerAlex** [comment]
I will use https://github.com/amoghe/go-crypt in the meantime, sadly it's cgo code with dependencies on a real unix system during build but works for now.

**Comment by tredoe** [comment]
Use version v1.5.0

**Comment by BirknerAlex** [comment]
Thanks @tredoe! Seems work fine now. 🎉

**Comment by jyothisjose** [comment]
@tredoe Thank you
