### ISSUE TITLE
sh module failing tests

### ISSUE THREAD

**Issue by alesage** [tredoe/osutil#8]
We see failing tests for sh module when building under Debian pbuilder environment:
```
=== RUN   TestRun
--- FAIL: TestRun (0.01s)
	sh_test.go:63: `ls ~/` (match): expected true, found false
	sh_test.go:67: `ls ~/`: output is empty
	sh_test.go:75: `find -name 'sh*.go'` (output): expected "./sh.go\n./sh_test.go\n", found "./sh_test.go\n./sh.go\n"
	sh_test.go:87: `LANG=C find -nop README.md` (error): expected "find: unknown predicate `-nop'", found "find: unknown predicate `-nop'\nTry 'find --help' for more information."
FAIL
FAIL	github.com/tredoe/osutil/sh	0.017s
```
Our stretch environments have findutils 4.6.0+git+20161106-2 .

Wonder if we're missing some Go env vars while attempting to package?

**Comment by tredoe** [comment]
It that module is failling, it is because those commands are not working in your system. To check it, clone the project and change the directory to it; then, run every command:

`ls ~/`
...
